apiVersion: v2
name: my-monitoring
description: Helm chart for installing Prometheus, Grafana and Loki

type: application

version: 0.1.0

appVersion: "0.1.0"

dependencies:
- name: kube-prometheus-stack
  version: 41.4.0   # we will use particular version to simplify updates
  repository: https://prometheus-community.github.io/helm-charts
- name: loki-distributed
  version: 0.63.0   # we will use particular version to simplify updates
  repository: https://grafana.github.io/helm-charts
