# Values

namespace: &namespace-global monitoring

kube-prometheus-stack:
# Override deploy namespace
  namespaceOverride: *namespace-global
  defaultRules:
# Override runbooks URL if needed
    runbookUrl: "https://confluence.myorg.com/project/runbooks"
  grafana:
# Add loki datasource into Grafana
    additionalDataSources:
      - name: Loki
        type: loki
        url: "http://{{ tpl .Release.Name . }}-loki-distributed-gateway:3100/"
  prometheus:
    prometheusSpec:
      retention: 30d
loki-distributed:
  loki:
    config: |
      auth_enabled: false
      server:
        http_listen_port: 3100
        http_server_read_timeout: 30m
        http_server_write_timeout: 30m
        http_server_idle_timeout: 30m
      distributor:
        ring:
          kvstore:
            store: memberlist
          heartbeat_timeout: 30s
      memberlist:
        join_members:
          - {{ include "loki.fullname" . }}-memberlist
        dead_node_reclaim_time: 30s
        gossip_to_dead_nodes_time: 30s
        left_ingesters_timeout: 30s
      ingester:
        lifecycler:
          ring:
            kvstore:
              store: memberlist
            replication_factor: 3
            heartbeat_timeout: 30s
        chunk_idle_period: 30m
        chunk_block_size: 262144
        chunk_encoding: snappy
        chunk_retain_period: 1m
        max_transfer_retries: 0
        concurrent_flushes: 5000
        flush_check_period: 30s
        flush_op_timeout: 30m
        max_chunk_age: 1h
        wal:
          dir: /var/loki/wal
      limits_config:
        enforce_metric_name: false
        reject_old_samples: true
        reject_old_samples_max_age: 168h
        max_cache_freshness_per_query: 10m
        split_queries_by_interval: 15m
        max_streams_per_user: 0
        max_global_streams_per_user: 0
        max_cache_freshness_per_query: 10m
        max_entries_limit_per_query: 5000
        max_query_parallelism: 12
        max_query_length: 672h #28 days
        ingestion_rate_strategy: local
        ingestion_rate_mb: 15000
        ingestion_burst_size_mb: 25000
        per_stream_rate_limit: 1280MB
        per_stream_rate_limit_burst: 1920MB
        retention_period: 4320h # 180 days
      # Overriding storage related stuff for Loki
      schema_config:
        configs:
        - from: 2022-10-13
          store: aws
          object_store: s3
          schema: v11
          index:
            prefix: loki_
      storage_config:
        boltdb_shipper:
          shared_store: s3
          active_index_directory: /var/loki/index
          cache_location: /var/loki/cache
          cache_ttl: 336h
        aws:
          s3: s3://eu-central-1/my-loki-bucket
          s3forcepathstyle: true
          dynamodb:
            dynamodb_url: dynamodb://eu-central-1
      runtime_config:
        file: /var/{{ include "loki.name" . }}-runtime/runtime.yaml
      chunk_store_config:
        max_look_back_period: 0s
      table_manager:
        retention_deletes_enabled: false
        retention_period: 0s
      query_range:
        align_queries_with_step: true
        max_retries: 5
        cache_results: true
        results_cache:
          cache:
            enable_fifocache: true
            fifocache:
              max_size_items: 1024
              ttl: 24h
      querier:
        query_timeout: 30m
        query_ingesters_within: 15m
        tail_max_duration: 30m
        extra_query_delay: 15m
        max_concurrent: 16 #The maximum number of top-level PromQL queries that will execute at the same time, per querier process. If using the query frontend, this should be set to at least (-querier.worker-parallelism * number of query frontend replicas).
        engine:
          timeout: 30m
          max_look_back_period: 672h
      query_range:
        align_queries_with_step: true
        max_retries: 60
        split_queries_by_interval: 15m
        parallelise_shardable_queries: true
        cache_results: true
        results_cache:
          cache:
            enable_fifocache: true
            fifocache:
              validity: 120m



      frontend_worker:
        {{- if .Values.queryScheduler.enabled }}
        scheduler_address: {{ include "loki.querySchedulerFullname" . }}:9095
        {{- else }}
        frontend_address: {{ include "loki.queryFrontendFullname" . }}:9095
        {{- end }}
      frontend:
        log_queries_longer_than: 2m
        compress_responses: true
        {{- if .Values.queryScheduler.enabled }}
        scheduler_address: {{ include "loki.querySchedulerFullname" . }}:9095
        {{- end }}
        tail_proxy_url: http://{{ include "loki.querierFullname" . }}:3100
      compactor:
        shared_store: s3
        working_directory: /var/loki/compactor
        compaction_interval: 10m
        retention_enabled: true
        retention_delete_delay: 30m
        retention_delete_worker_count: 200
      ruler:
        storage:
          type: local
          local:
            directory: /etc/loki/rules
        ring:
          kvstore:
            store: memberlist
        rule_path: /tmp/loki/scratch
        alertmanager_url: http://{{ template "kube-prometheus-stack.fullname" . }}-alertmanager
        external_url: https://alertmanager.myorg.com
  ruler:
    enabled: true
